In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6]) # Creatiing 1- Dimentional array (1D)
b = np.array([7,8,9,10,11,12])
print (a)
print (b)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [ ]:
type(a) # nd: N-dimentional array

numpy.ndarray

# Operations and Method

In [5]:
print(a+b)
print(a-b)
print(a*b)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]


In [9]:
# Creating 2D array

a2 = np.array([[1,2,3], [4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Creating 3D array

a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# to check shape of an 2d, 3d array (or shows no. of rows and coloumns)o/p: (rows, coloumns)

print(a2.shape)
print(a3.shape)

(2, 3)
(2, 2, 3)


In [ ]:
# Shows no. of Dimentions

print(a2.ndim)
print(a3.ndim) 


2
3


In [ ]:
np.arange(10) # creating a list of values from 0 to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,11) # creating a list of values from 1 to 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,10,2) # creating a list of values from 1 to 10 within a gap of 2

array([1, 3, 5, 7, 9])

In [ ]:
# Creating 2D Array using random function
 # Size tells the no. of rows and columns

np.random.randint(1,21, size=(3,4))

array([[11, 13,  8, 13],
       [ 7, 18, 10,  8],
       [13,  4, 17, 17]], dtype=int32)

In [21]:
x = np.array([[7,2,3],[3,9,4],[3,4,5]])
y = np.array([[3,4,5],[3,9,4],[7,2,3]])
print(x)
print(y)

[[7 2 3]
 [3 9 4]
 [3 4 5]]
[[3 4 5]
 [3 9 4]
 [7 2 3]]


In [22]:
print(x*y)

[[21  8 15]
 [ 9 81 16]
 [21  8 15]]


In [ ]:
print(x@y) # Matrix Multiplication, @ symbol

[[ 48  52  52]
 [ 64 101  63]
 [ 56  58  46]]


In [ ]:
np.dot(x,y) # this method also used for matrix multiplication

array([[ 48,  52,  52],
       [ 64, 101,  63],
       [ 56,  58,  46]])

In [25]:
x.mean()

np.float64(4.444444444444445)

In [ ]:
round(x.mean()) # this will show the round off value of a mean value

4

In [27]:
print(x.sum())
print(x.var())
print(x.std())

40
4.469135802469136
2.1140330656044943


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,25))   #25th percentile
print(np.percentile(arr,50))   #50th percentile (median)
print(np.percentile(arr,75))   #75th percentile

3.0
5.0
7.0
